### PR TITLE
Always lookup lowercase uri in @resources

### PR DESCRIPTION
**Pull request by saebekassebil**
Fixes an issue that prevented playing and/or viewing the contents of a range of journals (Inspiration, etc).

### CODE REVIEW

**Comment by mzedeler** [comment]
Isn't this going to break servers that do the right thing (tm) with regard to casing? This looks like a materials issue. 

Sent from my Sony Xperia™ smartphone

---- Jakob Miland wrote ----

**Comment by saebekassebil** [comment]
Well, I guess it is a material issue, but I remember way back, that we decided to lowercase all resources, because there was a huge amount of books that didn't get it right.

Problem is we only did it halfway apparently.
https://github.com/Notalib/LYT/blob/master/src/models/book/book.coffee#L110

I was going to merge this and deploy, but I'll wait for an OK then :)

**Comment by saebekassebil** [comment]
Also see PR #630

**Comment by saebekassebil** [comment]
And no. It's not going to break any servers. It'll only break books with files that have similar filenames with different casings. (a.html and A.htMl). But I don't think this is anything to worry about and I kinda recall that it's prohibited by the DAISY standard for legacy reasons.

**Pull request merged**
